set default FC to gfortran
set default CC to gcc
set default CXX to g++
SASS_ROOT: /home/erosita/sw/eSASSdevel
package SASS
package EROSITA
setup complete
ero_vis: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory
make event directory
compute gti with ero_vis
Traceback (most recent call last):
  File "../simulate.py", line 203, in <module>
    data_dir).run_all()
  File "../simulate.py", line 157, in run_all
    self.compute_gti(self._simput)
  File "../simulate.py", line 115, in compute_gti
    subprocess.check_call(cmd)
  File "/home/comparat/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ero_vis', 'GTIfile=/data40s/erosim/eRASS/sixte/021/erass_SIMPUT_000021_1024.gti', 'Simput=/data17s/darksim/MD/MD_1.0Gpc/cat_AGN_SIMPUT/SIMPUT_000021_1024.fit', 'Exposure=31536000.000000', 'Attitude=/data40s/erosim/eRASS/eRASS_Pc87M55_3dobi_att_remeis.fits', 'TSTART=0.000000', 'dt=10.0', 'visibility_range=1.0', 'clobber=yes']' returned non-zero exit status 127.
ero_calevents: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory
['ero_calevents', 'Projection=AIT', 'Attitude=/data01s/erosim/eRASS/eRASS_Pc87M55_3dobi_att_remeis.fits', 'clobber=yes', 'EvtFile=/data01s/erosim/eRASS/sixte/021/erass_ccd1_evt.fits', 'eroEvtFile=/data01s/erosim/eRASS/sixte/021/cal_erass_ccd1_evt.fits', 'CCDNr=1', 'RA=1.5', 'Dec=0.0']
Traceback (most recent call last):
  File "../pre-process-esass.py", line 92, in <module>
    PrepareForEsass(ra_cen, dec_cen, data_dir).prep_and_merge()
  File "../pre-process-esass.py", line 81, in prep_and_merge
    self.cal_events()
  File "../pre-process-esass.py", line 42, in cal_events
    subprocess.check_call(cmd)
  File "/home/comparat/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ero_calevents', 'Projection=AIT', 'Attitude=/data01s/erosim/eRASS/eRASS_Pc87M55_3dobi_att_remeis.fits', 'clobber=yes', 'EvtFile=/data01s/erosim/eRASS/sixte/021/erass_ccd1_evt.fits', 'eroEvtFile=/data01s/erosim/eRASS/sixte/021/cal_erass_ccd1_evt.fits', 'CCDNr=1', 'RA=1.5', 'Dec=0.0']' returned non-zero exit status 127.
evtool: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
['/data40s/erosim/eRASS/sixte/021/products/021_EventList_post.fits'] /data40s/erosim/eRASS/sixte/021/products/ 1 post
['evtool', 'eventfiles=/data40s/erosim/eRASS/sixte/021/merged_erass.fits', 'outfile=/data40s/erosim/eRASS/sixte/021/products/021_EventList_post.fits', 'emin=0.1', 'emax=0.5', 'image=yes', 'rebin=128', 'size=4096', 'pattern=15']
Traceback (most recent call last):
  File "../esass.py", line 374, in <module>
    esass_pipeline.run_pipeline()
  File "../esass.py", line 117, in run_pipeline
    subprocess.check_call(cmd)
  File "/home/comparat/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['evtool', 'eventfiles=/data40s/erosim/eRASS/sixte/021/merged_erass.fits', 'outfile=/data40s/erosim/eRASS/sixte/021/products/021_EventList_post.fits', 'emin=0.1', 'emax=0.5', 'image=yes', 'rebin=128', 'size=4096', 'pattern=15']' returned non-zero exit status 127.
